using ExtendedXmlSerializer;
using ExtendedXmlSerializer.Configuration;
using Ies.Logo.DataType.Xml;

namespace Ies.Logo.DataType.ArAps
{
    public class ArApProfile : IConfigurationProfile
    {
        public static ArApProfile Default { get; } = new ArApProfile();

        private ArApProfile() { }

        public IConfigurationContainer Get(IConfigurationContainer parameter)
        {
            var configuration = parameter.Type<ArAp>();

            Configure(configuration);

            return configuration;
        }
        public static void Configure<T>(ITypeConfiguration<T> typeConfigurations) where T : ArAp
        {
            typeConfigurations.Configure();
            typeConfigurations.Name<T>("AR_AP");

            typeConfigurations
                 .Member(m => m.AccountType).Name("ACCOUNT_TYPE")
                 .Member(m => m.Code).Name("CODE")
                 .Member(m => m.Title).Name("TITLE")
                 .Member(m => m.Address1).Name("ADDRESS1")
                 .Member(m => m.Address2).Name("ADDRESS2")
                 .Member(m => m.DistrictCode).Name("DISTRICT_CODE")
                 .Member(m => m.District).Name("DISTRICT")
                 .Member(m => m.TownCode).Name("TOWN_CODE")
                 .Member(m => m.Town).Name("TOWN")
                 .Member(m => m.CityCode).Name("CITY_CODE")
                 .Member(m => m.City).Name("CITY")
                 .Member(m => m.CountryCode).Name("COUNTRY_CODE")
                 .Member(m => m.Country).Name("COUNTRY")
                 .Member(m => m.PostalCode).Name("POSTAL_CODE")
                 .Member(m => m.Telephone1).Name("TELEPHONE1")
                 .Member(m => m.Telephone1Code).Name("TELEPHONE1_CODE")
                 .Member(m => m.Telephone2).Name("TELEPHONE2")
                 .Member(m => m.Telephone2Code).Name("TELEPHONE2_CODE")
                 .Member(m => m.Fax).Name("FAX")
                 .Member(m => m.FaxCode).Name("FAX_CODE")
                 .Member(m => m.TaxId).Name("TAX_ID")
                 .Member(m => m.TaxOffice).Name("TAX_OFFICE")
                 .Member(m => m.TaxOfficeCode).Name("TAX_OFFICE_CODE")
                 .Member(m => m.Contact).Name("CONTACT")
                 .Member(m => m.DiscountRate).Name("DISCOUNT_RATE")
                 .Member(m => m.Email).Name("E_MAIL")
                 .Member(m => m.WebUrl).Name("WEB_URL")
                 .Member(m => m.ReminderType).Name("REMINDER_TYPE")
                 .Member(m => m.ReminderEmail).Name("REMINDER_EMAIL")
                 .Member(m => m.ReminderFax).Name("REMINDER_FAX")
                 .Member(m => m.CorrespLang).Name("CORRESP_LANG")
                 .Member(m => m.VatId).Name("VAT_ID")
                 .Member(m => m.Blocked).Name("BLOCKED")
                 .Member(m => m.BankId1).Name("BANK_ID1")
                 .Member(m => m.BankId2).Name("BANK_ID2")
                 .Member(m => m.BankId3).Name("BANK_ID3")
                 .Member(m => m.BankId4).Name("BANK_ID4")
                 .Member(m => m.BankId5).Name("BANK_ID5")
                 .Member(m => m.BankId6).Name("BANK_ID6")
                 .Member(m => m.BankId7).Name("BANK_ID7")
                 .Member(m => m.BankName1).Name("BANK_NAME1")
                 .Member(m => m.BankName2).Name("BANK_NAME2")
                 .Member(m => m.BankName3).Name("BANK_NAME3")
                 .Member(m => m.BankName4).Name("BANK_NAME4")
                 .Member(m => m.BankName5).Name("BANK_NAME5")
                 .Member(m => m.BankName6).Name("BANK_NAME6")
                 .Member(m => m.BankName7).Name("BANK_NAME7")
                 .Member(m => m.BankAccount1).Name("BANK_ACCOUNT1")
                 .Member(m => m.BankAccount2).Name("BANK_ACCOUNT2")
                 .Member(m => m.BankAccount3).Name("BANK_ACCOUNT3")
                 .Member(m => m.BankAccount4).Name("BANK_ACCOUNT4")
                 .Member(m => m.BankAccount5).Name("BANK_ACCOUNT5")
                 .Member(m => m.BankAccount6).Name("BANK_ACCOUNT6")
                 .Member(m => m.BankAccount7).Name("BANK_ACCOUNT7")
                 .Member(m => m.DeliveryMethod).Name("DELIVERY_METHOD")
                 .Member(m => m.ShipmentAgent).Name("SHIPMENT_AGENT")
                 .Member(m => m.Currency).Name("CURRENCY")
                 .Member(m => m.EcommId).Name("E_COMM_ID")
                 .Member(m => m.DebtTrckType).Name("DEBT_TRCK_TYPE")
                 .Member(m => m.XrtdifType).Name("XRTDIF_TYPE")
                 .Member(m => m.CreditType).Name("CREDIT_TYPE")
                 .Member(m => m.CreditLimit).Name("CREDIT_LIMIT")
                 .Member(m => m.CreditBalanced).Name("CREDIT_BALANCED")
                 .Member(m => m.RiskFactChq).Name("RISKFACT_CHQ")
                 .Member(m => m.RiskFactPromnt).Name("RISKFACT_PROMNT")
                 .Member(m => m.ActionCredhold).Name("ACTION_CREDHOLD")
                 .Member(m => m.GlCode).Name("GL_CODE")
                 .Member(m => m.OhpCode).Name("OHP_CODE")
                 .Member(m => m.PpGroupCode).Name("PP_GROUP_CODE")
                 .Member(m => m.UseRepRisk).Name("USE_REP_RISK")
                 .Member(m => m.RiskLimit).Name("RISK_LIMIT")
                 .Member(m => m.RiskBalanced).Name("RISK_BALANCED")
                 .Member(m => m.OrdSendMethod).Name("ORD_SEND_METHOD")
                 .Member(m => m.OrdSendEmail).Name("ORD_SEND_EMAIL")
                 .Member(m => m.OrdSendFax).Name("ORD_SEND_FAX")
                 .Member(m => m.DspSendMethod).Name("DSP_SEND_METHOD")
                 .Member(m => m.DspSendEmail).Name("DSP_SEND_EMAIL")
                 .Member(m => m.DspSendFax).Name("DSP_SEND_FAX")
                 .Member(m => m.InvSendMethod).Name("INV_SEND_METHOD")
                 .Member(m => m.InvSendEmail).Name("INV_SEND_EMAIL")
                 .Member(m => m.InvSendFax).Name("INV_SEND_FAX")
                 .Member(m => m.SubscriberStatus).Name("SUBSCRIBER_STATUS")
                 .Member(m => m.SubscriberExt).Name("SUBSCRIBER_EXT")
                 .Member(m => m.AutoPaidBank).Name("AUTO_PAID_BANK")
                 .Member(m => m.PaymentType).Name("PAYMENT_TYPE")
                 .Member(m => m.LastSendRemLev).Name("LAST_SEND_REM_LEV")
                 .Member(m => m.ExtAccFlags).Name("EXT_ACC_FLAGS")
                 .Member(m => m.OrdSendFormat).Name("ORD_SEND_FORMAT")
                 .Member(m => m.DspSendFormat).Name("DSP_SEND_FORMAT")
                 .Member(m => m.InvSendFormat).Name("INV_SEND_FORMAT")
                 .Member(m => m.RemSendFormat).Name("REM_SEND_FORMAT")
                 .Member(m => m.StoreCreditCardNo).Name("STORE_CREDIT_CARD_NO")
                 .Member(m => m.ClOrdFreq).Name("CL_ORD_FREQ")
                 .Member(m => m.OrdDay).Name("ORD_DAY")
                 .Member(m => m.LidConfirmed).Name("LID_Confirmed")
                 .Member(m => m.EbsnsSendType).Name("E_BSNS_SEND_TYPE")
                 .Member(m => m.LdxDefOrderStat).Name("LDX_DEF_ORDER_STAT")
                 .Member(m => m.LdxDefOrderPrc).Name("LDX_DEF_ORDER_PRC")
                 .Member(m => m.ItrSendMethod).Name("ITR_SEND_METHOD")
                 .Member(m => m.ItrSendMailAdr).Name("ITR_SEND_MAIL_ADR")
                 .Member(m => m.ItrSendFax).Name("ITR_SEND_FAX")
                 .Member(m => m.ItrSendFormat).Name("ITR_SEND_FORMAT")
                 .Member(m => m.Img2Inc).Name("IMG2INC")
                 .Member(m => m.CellPhone).Name("CELL_PHONE")
                 .Member(m => m.Itext).Name("ITEXT")
                 .Member(m => m.InvoicePrntCnt).Name("INVOICE_PRNT_CNT")
                 .Member(m => m.WfLowCardRef).Name("WFLOWCARDREF")
                 .Member(m => m.ParentClCode).Name("PARENTCLCODE")
                 .Member(m => m.CodeChanged).Name("CODE_CHANGED")
                 .Member(m => m.CollectInv).Name("COLLECTINV")
                 .Member(m => m.PieceOrdInflict).Name("PIECEORDINFLICT")
                 .Member(m => m.PurchBrws).Name("PURCHBRWS")
                 .Member(m => m.SalesBrws).Name("SALESBRWS")
                 .Member(m => m.ImpBrws).Name("IMPBRWS")
                 .Member(m => m.ExpBrws).Name("EXPBRWS")
                 .Member(m => m.FinBrws).Name("FINBRWS")
                 .Member(m => m.CollatrlRiskType).Name("COLLATRLRISK_TYPE")
                 .Member(m => m.CollRiskOver).Name("COLLRISK_OVER")
                 .Member(m => m.CollRiskOrdRiskOver).Name("COLLRISK_ORD_RISK_OVER")
                 .Member(m => m.CollRiskDespRiskOver).Name("COLLRISK_DESP_RISK_OVER")
                 .Member(m => m.CollRiskUseRepRisk).Name("COLLRISK_USE_REP_RISK")
                 .Member(m => m.CollRiskPcollatrlTotal).Name("COLLRISK_PCOLLATRL_TOTAL")
                 .Member(m => m.CollRiskRepPcollatrlTot).Name("COLLRISK_REP_PCOLLATRL_TOT")
                 .Member(m => m.CollRiskScollatrlTotal).Name("COLLRISK_SCOLLATRL_TOTAL")
                 .Member(m => m.CollRiskTotal).Name("COLLRISK_TOTAL")
                 .Member(m => m.CollRiskRepRiskTotal).Name("COLLRISK_REP_RISK_TOTAL")
                 .Member(m => m.CollRiskDespTotal).Name("COLLRISK_DESP_TOTAL")
                 .Member(m => m.CollRiskRepDespRiskTot).Name("COLLRISK_REP_DESP_RISK_TOT")
                 .Member(m => m.CollRiskLimit).Name("COLLRISK_LIMIT")
                 .Member(m => m.CollRiskRepLimit).Name("COLLRISK_REP_LIMIT")
                 .Member(m => m.CollRiskBalanced).Name("COLLRISK_BALANCED")
                 .Member(m => m.CollRiskRepBalanced).Name("COLLRISK_REP_BALANCED")
                 .Member(m => m.CollRiskOrdRiskTotal).Name("COLLRISK_ORD_RISK_TOTAL")
                 .Member(m => m.CollRiskRepOrdRiskTot).Name("COLLRISK_REP_ORD_RISK_TOT")
                 .Member(m => m.CollRiskOrdRiskTotSugg).Name("COLLRISK_ORD_RISK_TOT_SUGG")
                 .Member(m => m.CollRiskRepOrdRiskTotSug).Name("COLLRISK_REP_ORD_RISK_TOT_SUG")
                 .Member(m => m.GrpFirmNr).Name("GRPFIRMNR")
                 .Member(m => m.ConsCode).Name("CONSCODE")
                 .Member(m => m.EbankCode).Name("EBANKCODE")
                 .Member(m => m.OffSendMethod).Name("OFF_SEND_METHOD")
                 .Member(m => m.OffSendMailAddr).Name("OFF_SEND_MAIL_ADDR")
                 .Member(m => m.OffSendFax).Name("OFF_SEND_FAX")
                 .Member(m => m.OffSendFormat).Name("OFF_SEND_FORMAT")
                 .Member(m => m.RiskType1).Name("RISK_TYPE1")
                 .Member(m => m.RiskType2).Name("RISK_TYPE2")
                 .Member(m => m.RiskType3).Name("RISK_TYPE3")
                 .Member(m => m.RiskGrpControl).Name("RISK_GRP_CONTROL")
                 .Member(m => m.ActionCredHoldOrd).Name("ACTION_CREDHOLD_ORD")
                 .Member(m => m.ActionCredHoldDesp).Name("ACTION_CREDHOLD_DESP")
                 .Member(m => m.ActionCredHoldAcc).Name("ACTION_CREDHOLD_ACC")
                 .Member(m => m.ActionCredHoldMyCs).Name("ACTION_CREDHOLD_MY_CS")
                 .Member(m => m.RiskCtrlType).Name("RISK_CTRL_TYPE")
                 .Member(m => m.AccRiskTotal).Name("ACC_RISK_TOTAL")
                 .Member(m => m.RepAccRiskTotal).Name("REP_ACC_RISK_TOTAL")
                 .Member(m => m.CstCsRiskTotal).Name("CST_CS_RISK_TOTAL")
                 .Member(m => m.RepCstCsRiskTotal).Name("REP_CST_CS_RISK_TOTAL")
                 .Member(m => m.MyCsRiskTotal).Name("MY_CS_RISK_TOTAL")
                 .Member(m => m.RepMyCsRiskTotal).Name("REP_MY_CS_RISK_TOTAL")
                 .Member(m => m.OrdRiskTotal).Name("ORD_RISK_TOTAL")
                 .Member(m => m.RepOrdRiskTotal).Name("REP_ORD_RISK_TOTAL")
                 .Member(m => m.OrdRiskTotalSugg).Name("ORD_RISK_TOTAL_SUGG")
                 .Member(m => m.RepOrdRiskTotalSugg).Name("REP_ORD_RISK_TOTAL_SUGG")
                 .Member(m => m.DespRiskTotal).Name("DESP_RISK_TOTAL")
                 .Member(m => m.RepDespRiskTotal).Name("REP_DESP_RISK_TOTAL")
                 .Member(m => m.AccRiskLimit).Name("ACC_RISK_LIMIT")
                 .Member(m => m.RepAccRiskLimit).Name("REP_ACC_RISK_LIMIT")
                 .Member(m => m.CstCsRiskLimit).Name("CST_CS_RISK_LIMIT")
                 .Member(m => m.RepCstCsRiskLimit).Name("REP_CST_CS_RISK_LIMIT")
                 .Member(m => m.MyCsRiskLimit).Name("MY_CS_RISK_LIMIT")
                 .Member(m => m.RepMyCsRiskLimit).Name("REP_MY_CS_RISK_LIMIT")
                 .Member(m => m.DespRiskLimit).Name("DESP_RISK_LIMIT")
                 .Member(m => m.RepDespRiskLimit).Name("REP_DESP_RISK_LIMIT")
                 .Member(m => m.OrdRiskLimit).Name("ORD_RISK_LIMIT")
                 .Member(m => m.RepOrdRiskLimit).Name("REP_ORD_RISK_LIMIT")
                 .Member(m => m.OrdRiskLimitSugg).Name("ORD_RISK_LIMIT_SUGG")
                 .Member(m => m.RepOrdSirkLimitSugg).Name("REP_ORD_SIRK_LIMIT_SUGG")
                 .Member(m => m.AccRiskBalanced).Name("ACC_RISK_BALANCED")
                 .Member(m => m.RepAccRiskBalanced).Name("REP_ACC_RISK_BALANCED")
                 .Member(m => m.CstCsRiskBalanced).Name("CST_CS_RISK_BALANCED")
                 .Member(m => m.RepCstCsRiskBalanced).Name("REP_CST_CS_RISK_BALANCED")
                 .Member(m => m.MyCsRiskBalanced).Name("MY_CS_RISK_BALANCED")
                 .Member(m => m.RepMyCsRiskBalanced).Name("REP_MY_CS_RISK_BALANCED")
                 .Member(m => m.DespRiskBalanced).Name("DESP_RISK_BALANCED")
                 .Member(m => m.RepDespRiskBalanced).Name("REP_DESP_RISK_BALANCED")
                 .Member(m => m.OrdRiskBalanced).Name("ORD_RISK_BALANCED")
                 .Member(m => m.RepOrdRiskBalanced).Name("REP_ORD_RISK_BALANCED")
                 .Member(m => m.OrdRiskBalancedSugg).Name("ORD_RISK_BALANCED_SUGG")
                 .Member(m => m.RepOrdRiskBalancedSugg).Name("REP_ORD_RISK_BALANCED_SUGG")
                 .Member(m => m.LoanGrpCtrl).Name("LOAN_GRP_CTRL")
                 .Member(m => m.EbusDataSendType).Name("EBUS_DATA_SEND_TYPE")
                 .Member(m => m.IniStatusFlags).Name("INI_STATUS_FLAGS")
                 .Member(m => m.SlsOrderStatus).Name("SLS_ORDER_STATUS")
                 .Member(m => m.SlsOrderPrice).Name("SLS_ORDER_PRICE")
                 .Member(m => m.SameItemCodeUse).Name("SAME_ITEM_CODE_USE")
                 .Member(m => m.ImageSize).Name("IMAGE_SIZE")
                 .Member(m => m.MapId).Name("MAP_ID")
                 .Member(m => m.Longitude).Name("LONGITUDE")
                 .Member(m => m.Latitude).Name("LATITUDE")
                 .Member(m => m.CityId).Name("CITY_ID")
                 .Member(m => m.TownId).Name("TOWN_ID")
                 .Member(m => m.BankIban1).Name("BANK_IBAN1")
                 .Member(m => m.BankIban2).Name("BANK_IBAN2")
                 .Member(m => m.BankIban3).Name("BANK_IBAN3")
                 .Member(m => m.BankIban4).Name("BANK_IBAN4")
                 .Member(m => m.BankIban5).Name("BANK_IBAN5")
                 .Member(m => m.BankIban6).Name("BANK_IBAN6")
                 .Member(m => m.BankIban7).Name("BANK_IBAN7")
                 .Member(m => m.BankBic1).Name("BANK_BIC1")
                 .Member(m => m.BankBic2).Name("BANK_BIC2")
                 .Member(m => m.BankBic3).Name("BANK_BIC3")
                 .Member(m => m.BankBic4).Name("BANK_BIC4")
                 .Member(m => m.BankBic5).Name("BANK_BIC5")
                 .Member(m => m.BankBic6).Name("BANK_BIC6")
                 .Member(m => m.BankBic7).Name("BANK_BIC7")
                 .Member(m => m.PersCompany).Name("PERSCOMPANY")
                 .Member(m => m.Tckno).Name("TCKNO")
                 .Member(m => m.ExtSendMethod).Name("EXT_SEND_METHOD")
                 .Member(m => m.ExtSendEmail).Name("EXT_SEND_EMAIL")
                 .Member(m => m.ExtSendFax).Name("EXT_SEND_FAX")
                 .Member(m => m.ExtSendFormat).Name("EXT_SEND_FORMAT")
                 .Member(m => m.AddTorefList).Name("ADDTOREFLIST")
                 .Member(m => m.OrdRiskOverSugg).Name("ORD_RISK_OVER_SUGG")
                 .Member(m => m.CashCode).Name("CASH_CODE")
                 .Member(m => m.UsedInPeriods).Name("USED_IN_PERIODS")
                 .Member(m => m.Contact2).Name("CONTACT2")
                 .Member(m => m.Contact3).Name("CONTACT3")
                 .Member(m => m.Email2).Name("E_MAIL2")
                 .Member(m => m.Email3).Name("E_MAIL3")
                 .Member(m => m.RsklimCntrl).Name("RSKLIM_CNTRL")
                 .Member(m => m.DueDateCntrl).Name("DUEDATE_CNTRL")
                 .Member(m => m.AgingCntrl).Name("AGING_CNTRL")
                 .Member(m => m.AgingDay).Name("AGING_DAY")
                 .Member(m => m.AcceptEinvy).Name("ACCEPT_EINV")
                 .Member(m => m.EinvoiceId).Name("EINVOICEID")
                 .Member(m => m.ProfileId).Name("PROFILE_ID")
                 .Member(m => m.PurchOrderStatus).Name("PURC_ORDER_STATUS")
                 .Member(m => m.PurcOrderPrice).Name("PURC_ORDER_PRICE");

            typeConfigurations
                 .Member(m => m.EinvoiceType).Name("EINVOICE_TYPE")
                 .Member(m => m.Title2).Name("TITLE2")
                 .Member(m => m.TelephoneExtension1).Name("TELEPHONE_EXTENSION1")
                 .Member(m => m.TelephoneExtension2).Name("TELEPHONE_EXTENSION2")
                 .Member(m => m.FaxExtension).Name("FAX_EXTENSION")
                 .Member(m => m.IsForeign).Name("ISFOREIGN")
                 .Member(m => m.PostLabel).Name("POST_LABEL")
                 .Member(m => m.SenderLabel).Name("SENDER_LABEL")
                 .Member(m => m.Name).Name("NAME")
                 .Member(m => m.Surname).Name("SURNAME")
                 .Member(m => m.LabelInfo).Name("LABEL_INFO")
                 .Member(m => m.InsteadOfDispatch).Name("INSTEAD_OF_DISPATCH")
                 ;
        }
    }
}
