using ExtendedXmlSerializer;
using ExtendedXmlSerializer.Configuration;
using Ies.Logo.DataType.Xml;

namespace Ies.Logo.DataType.Invoices
{
    public class TransactionProfile : IConfigurationProfile
    {
        public static TransactionProfile Default { get; } = new TransactionProfile();

        private TransactionProfile() { }

        public IConfigurationContainer Get(IConfigurationContainer parameter)
        {
            var configuration = parameter.Type<Transaction>();

            Configure(configuration);

            return configuration;
        }

        public static void Configure<T>(ITypeConfiguration<T> typeConfigurations) where T : Transaction
        {
            typeConfigurations.Configure();
            typeConfigurations.Name<T>("TRANSACTION");

            typeConfigurations
                .Member(m => m.FaInfo).Name("FA_INFO")
                .Member(m => m.SlDetails).Name("SL_DETAILS")
                .Member(m => m.Details).Name("DETAILS")
                .Member(m => m.QcList).Name("QCLIST")
                .Member(m => m.CampaingInfos).Name("CAMPAIGN_INFOS")
                .Member(m => m.GeniusFldsList).Name("GENIUSFLDSLIST")
                .Member(m => m.DefnFldsList).Name("DEFNFLDSLIST")
                .Member(m => m.FaregDefnFldList).Name("FAREGDEFNFLDLIST")
                .Member(m => m.PreAccLines).Name("PREACCLINES")
                .Member(m => m.Type).Name("TYPE")
                .Member(m => m.MasterCode).Name("MASTER_CODE")
                .Member(m => m.MasterDef).Name("MASTER_DEF")
                .Member(m => m.DetailLevel).Name("DETAIL_LEVEL")
                .Member(m => m.DiscExpCalc).Name("DISCEXP_CALC")
                .Member(m => m.SourceCostGrp).Name("SOURCECOSTGRP")
                .Member(m => m.OrderReference).Name("ORDER_REFERENCE")
                .Member(m => m.OrderSite).Name("ORDER_SITE")
                .Member(m => m.PromotionCode).Name("PROMOTION_CODE")
                .Member(m => m.DelvryCode).Name("DELVRY_CODE")
                .Member(m => m.Quantity).Name("QUANTITY")
                .Member(m => m.Price).Name("PRICE")
                .Member(m => m.Total).Name("TOTAL")
                .Member(m => m.CurrPrice).Name("CURR_PRICE")
                .Member(m => m.PcPrice).Name("PC_PRICE")
                .Member(m => m.CurrTransaction).Name("CURR_TRANSACTION")
                .Member(m => m.TcXrate).Name("TC_XRATE")
                .Member(m => m.RcXrate).Name("RC_XRATE")
                .Member(m => m.CostDistr).Name("COST_DISTR")
                .Member(m => m.DiscountDistr).Name("DISCOUNT_DISTR")
                .Member(m => m.ExpenseDistr).Name("EXPENSE_DISTR")
                .Member(m => m.PromotionDistr).Name("PROMOTION_DISTR")
                .Member(m => m.DiscountRate).Name("DISCOUNT_RATE")
                .Member(m => m.BaseAmount).Name("BASE_AMOUNT")
                .Member(m => m.Description).Name("DESCRIPTION")
                .Member(m => m.UnitConv9).Name("UNIT_CONV9")
                .Member(m => m.VatIncluded).Name("VAT_INCLUDED")
                .Member(m => m.VatRate).Name("VAT_RATE")
                .Member(m => m.VatAmount).Name("VAT_AMOUNT")
                .Member(m => m.VatBase).Name("VAT_BASE")
                .Member(m => m.VatAdjustment).Name("VAT_ADJUSTMENT")
                .Member(m => m.Billed).Name("BILLED")
                .Member(m => m.Composite).Name("COMPOSITE")
                .Member(m => m.RetCostType).Name("RET_COST_TYPE")
                .Member(m => m.SourceSite).Name("SOURCE_SITE")
                .Member(m => m.SourceReference).Name("SOURCE_REFERENCE")
                .Member(m => m.RetCost).Name("RET_COST")
                .Member(m => m.TcRetCost).Name("TC_RETCOST")
                .Member(m => m.OutCost).Name("OUT_COST")
                .Member(m => m.TcOutCost).Name("TC_OUTCOST")
                .Member(m => m.FixastCode).Name("FIXAST_CODE")
                .Member(m => m.FixastStatus).Name("FIXAST_STATUS")
                .Member(m => m.TotalNet).Name("TOTAL_NET")
                .Member(m => m.PriceUpdCost).Name("PRICE_UPDCOST")
                .Member(m => m.PriceUpdNeg).Name("PRICE_UPDNEG")
                .Member(m => m.ProdExpnDistr).Name("PROD_EXPN_DISTR")
                .Member(m => m.RcPriceUpd).Name("RC_PRICE_UPD")
                .Member(m => m.RcPriceUpdCost).Name("RC_PRICE_UPDCOST")
                .Member(m => m.OutputCode).Name("OUTPUT_CODE")
                .Member(m => m.CostRate).Name("COST_RATE")
                .Member(m => m.QcOk).Name("QC_OK")
                .Member(m => m.NetDscFlag).Name("NET_DSC_FLAG")
                .Member(m => m.NetDscRate).Name("NET_DSC_RATE")
                .Member(m => m.NetDscAmount).Name("NET_DSC_AMOUNT")
                .Member(m => m.DispatchNumber).Name("DISPATCH_NUMBER")
                .Member(m => m.DistOrdSiteId).Name("DIST_ORD_SITEIID")
                .Member(m => m.DistOrdReference).Name("DIST_ORD_REFERENCE")
                .Member(m => m.CampaingPoint).Name("CAMPAIGN_POINT")
                .Member(m => m.PromClasItemCode).Name("PROM_CLAS_ITEM_CODE")
                .Member(m => m.VendComm).Name("VEND_COMM")
                .Member(m => m.PrevOutCost).Name("PREV_OUT_COST")
                .Member(m => m.CostOfSaleGlCode).Name("COST_OF_SALE_GL_CODE")
                .Member(m => m.PurchGlCode).Name("PURCH_GL_CODE")
                .Member(m => m.CostOfSaleOhpCode).Name("COST_OF_SALE_OHP_CODE")
                .Member(m => m.PurchOhpCode).Name("PURCH_OHP_CODE")
                .Member(m => m.PrevOutCostCurr).Name("PREV_OUT_COST_CURR")
                .Member(m => m.EuVatAmount).Name("EU_VAT_AMOUNT")
                .Member(m => m.EuVatStatus).Name("EU_VAT_STATUS")
                .Member(m => m.PrRate).Name("PR_RATE")
                .Member(m => m.AddTaxRate).Name("ADD_TAX_RATE")
                .Member(m => m.AddTaxConvFact).Name("ADD_TAX_CONV_FACT")
                .Member(m => m.AddTaxAmount).Name("ADD_TAX_AMOUNT")
                .Member(m => m.AddTaxPrCost).Name("ADD_TAX_PRCOST")
                .Member(m => m.AddTaxRetCost).Name("ADD_TAX_RETCOST")
                .Member(m => m.AddTaxRetCostCurr).Name("ADD_TAX_RETCOSTCURR")
                .Member(m => m.GrossuInfo1).Name("GROSS_U_INFO1")
                .Member(m => m.GrossuInfo2).Name("GROSS_U_INFO2")
                .Member(m => m.AddTaxPrCostCurr).Name("ADD_TAX_PRCOSTCURR")
                .Member(m => m.AddTaxAmntIsUpd).Name("ADD_TAX_AMNT_IS_UPD")
                .Member(m => m.PlnSttransPerNr).Name("PLN_STTRANS_PER_NR")
                .Member(m => m.PordClsPlnAmnt).Name("PORD_CLS_PLN_AMNT")
                .Member(m => m.PlnSttransReference).Name("PLN_STTRANS_REFERENCE")
                .Member(m => m.PlnAmount).Name("PLN_AMOUNT")
                .Member(m => m.InflationIdx).Name("INFLATION_IDX")
                .Member(m => m.EdtCurr).Name("EDT_CURR")
                .Member(m => m.EdtPrice).Name("EDT_PRICE")
                .Member(m => m.PrdordTotCoef).Name("PRDORD_TOT_COEF")
                .Member(m => m.DempeggedAmnt).Name("DEMPEGGED_AMNT")
                .Member(m => m.StdunitCost).Name("STDUNIT_COST")
                .Member(m => m.StdrpunitCost).Name("STDRPUNIT_COST")
                .Member(m => m.Infldx).Name("INFLDX")
                .Member(m => m.CostdiffAccCode).Name("COSTDIFF_ACCCODE")
                .Member(m => m.CostdiffCenCode).Name("COSTDIFF_CENCODE")
                .Member(m => m.AddTaxDiscAmnt).Name("ADDTAXDISC_AMNT")
                .Member(m => m.OrgLogoId).Name("ORGLOGOID")
                .Member(m => m.EximFicheNo).Name("EXIM_FICHENO")
                .Member(m => m.SalesmanCode).Name("SALEMANCODE")
                .Member(m => m.EximFicheType).Name("EXIM_FICHE_TYPE")
                .Member(m => m.TransExpLine).Name("TRANS_EXP_LINE")
                .Member(m => m.InsExpLine).Name("INS_EXP_LINE")
                .Member(m => m.EximProcNo).Name("EXIM_PROC_NO")
                .Member(m => m.EximFileCode).Name("EXIM_FILE_CODE")
                .Member(m => m.EximFileLineNr).Name("EXIM_FILELINENR")
                .Member(m => m.EximWhFicheNo).Name("EXIM_WHFICHE_NO")
                .Member(m => m.EximWhFicheLnno).Name("EXIM_WHFICHE_LNNO")
                .Member(m => m.DiibCode).Name("DIIB_CODE")
                .Member(m => m.Month).Name("MONTH")
                .Member(m => m.Year).Name("YEAR")
                .Member(m => m.Pordsymoutln).Name("PORDSYMOUTLN")
                .Member(m => m.ExAddTaxRate).Name("EXADDTAXRATE")
                .Member(m => m.ExAddTaxConvf).Name("EXADDTAXCONVF")
                .Member(m => m.ExAddTaxaCode).Name("EXADDTAXACODE")
                .Member(m => m.ExAddTaxcCode).Name("EXADDTAXCCODE")
                .Member(m => m.OthrAddTaxaCode).Name("OTHRADDTAXACODE")
                .Member(m => m.OthrAddTaxcCode).Name("OTHRADDTAXCCODE")
                .Member(m => m.ExAddTaxAmnt).Name("EXADDTAXAMNT")
                .Member(m => m.AffectCollatrl).Name("AFFECT_COLLATRL")
                .Member(m => m.FromOrdWithPay).Name("FROMORDWITHPAY")
                .Member(m => m.VariantCode).Name("VARIANTCODE")
                .Member(m => m.VariantName).Name("VARIANTNAME")
                .Member(m => m.CanConfig).Name("CANCONFIG")
                .Member(m => m.AddTaxEffectKdv).Name("ADD_TAX_EFFECT_KDV")
                .Member(m => m.AffectRisk).Name("AFFECT_RISK")
                .Member(m => m.AddTaxVatMatrah).Name("ADD_TAX_VAT_MATRAH")
                .Member(m => m.ExchlineAddTaxVatMatrah).Name("EXCHLINE_ADD_TAX_VAT_MATRAH")
                .Member(m => m.AddTaxCode).Name("ADD_TAX_CODE")
                .Member(m => m.AddTaxGlobalCode).Name("ADDTAX_GLOBAL_CODE")
                .Member(m => m.UnitGlobalCode).Name("UNIT_GLOBAL_CODE")
                .Member(m => m.PayplGlobalCode).Name("PAYPL_GLOBAL_CODE")
                .Member(m => m.PrcurrGlobalCode).Name("PRCURR_GLOBAL_CODE")
                .Member(m => m.TrcurrGlobalCode).Name("TRCURR_GLOBAL_CODE")
                .Member(m => m.EdtcurrGlobalCode).Name("EDTCURR_GLOBAL_CODE")
                .Member(m => m.CanDeduct).Name("CANDEDUCT")
                .Member(m => m.MainMtReference).Name("MAIN_MT_REFERENCE")
                .Member(m => m.MainMtSiteId).Name("MAIN_MT_SITEID")
                .Member(m => m.PrclistCode).Name("PRCLISTCODE")
                .Member(m => m.PrclistType).Name("PRCLISTTYPE")
                .Member(m => m.FaplGlCode).Name("FAPL_GL_CODE")
                .Member(m => m.FaplOhpCode).Name("FAPL_OHP_CODE")
                .Member(m => m.DeductCode).Name("DEDUCT_CODE")
                .Member(m => m.DeductDef).Name("DEDUCT_DEF")
                .Member(m => m.DeductionPart1).Name("DEDUCTION_PART1")
                .Member(m => m.DeductionPart2).Name("DEDUCTION_PART2")
                .Member(m => m.DeductionTot).Name("DEDUCTION_TOT")
                .Member(m => m.DeductionTotTc).Name("DEDUCTION_TOT_TC")
                .Member(m => m.Guid).Name("GUID")
                .Member(m => m.FadGlCode).Name("FAD_GL_CODE")
                .Member(m => m.AuxilCode2).Name("AUXIL_CODE2")
                .Member(m => m.VatExceptReason).Name("VATEXCEPT_REASON")
                .Member(m => m.VatExceptCode).Name("VATEXCEPT_CODE")
                .Member(m => m.AddTaxExceptReason).Name("ADDTAXEXCEPT_REASON")
                .Member(m => m.AddTaxExceptCode).Name("ADDTAXEXCEPT_CODE")
                .Member(m => m.Barcode).Name("BARCODE")
                ;
        }
    }
}
