using ExtendedXmlSerializer;
using ExtendedXmlSerializer.Configuration;
using Logo.DataType.Xml;

namespace Logo.DataType.Dispatches
{
    public class DispatchProfile : IConfigurationProfile
    {
        public static DispatchProfile Default { get; } = new DispatchProfile();

        private DispatchProfile() { }

        public IConfigurationContainer Get(IConfigurationContainer parameter)
        {
            var configuration = parameter.Type<Dispatch>();

            Configure(configuration);

            return configuration;
        }

        public static void Configure<T>(ITypeConfiguration<T> typeConfigurations) where T : Dispatch
        {
            typeConfigurations.Configure();
            typeConfigurations.Name<T>("DISPATCH");

            typeConfigurations
                .Member(m => m.Number).Name("NUMBER")
                .Member(m => m.Type).Name("TYPE")
                .Member(m => m.DefnFldsList).Name("DEFNFLDSLIST")
                .Member(m => m.Transactions).Name("TRANSACTIONS")
                .Member(m => m.DocTrackNr).Name("DOC_TRACK_NR")
                .Member(m => m.Date).Name("DATE")
                .Member(m => m.Time).Name("TIME")
                .Member(m => m.DocNumber).Name("DOC_NUMBER")
                .Member(m => m.DocDate).Name("DOC_DATE")
                .Member(m => m.InvoiceNumber).Name("INVOICE_NUMBER")
                .Member(m => m.ArpCode).Name("ARP_CODE")
                .Member(m => m.ArpCodeShpm).Name("ARP_CODE_SHPM")
                .Member(m => m.ShiplocCode).Name("SHIPLOC_CODE")
                .Member(m => m.GlCode).Name("GL_CODE")
                .Member(m => m.OhpCode).Name("OHP_CODE")
                .Member(m => m.PorderNumber).Name("PORDER_NUMBER")
                .Member(m => m.SourceType).Name("SOURCE_TYPE")
                .Member(m => m.SourceWh).Name("SOURCE_WH")
                .Member(m => m.SourceWsCode).Name("SOURCEWSCODE")
                .Member(m => m.SourceCostGrp).Name("SOURCE_COST_GRP")
                .Member(m => m.DestType).Name("DEST_TYPE")
                .Member(m => m.DestWh).Name("DEST_WH")
                .Member(m => m.DestWsCode).Name("DESTWSCODE")
                .Member(m => m.DestCostGrp).Name("DEST_COST_GRP")
                .Member(m => m.DestDivision).Name("DEST_DIVISION")
                .Member(m => m.DestDepartment).Name("DEST_DEPARTMENT")
                .Member(m => m.DestFactory).Name("DEST_FACTORY")
                .Member(m => m.ProdStatus).Name("PROD_STATUS")
                .Member(m => m.InvoiceType).Name("INVOICE_TYPE")
                .Member(m => m.AddDiscounts).Name("ADD_DISCOUNTS")
                .Member(m => m.TotalDiscounts).Name("TOTAL_DISCOUNTS")
                .Member(m => m.TotalDiscounted).Name("TOTAL_DISCOUNTED")
                .Member(m => m.AddExpenses).Name("ADD_EXPENSES")
                .Member(m => m.TotalExpenses).Name("TOTAL_EXPENSES")
                .Member(m => m.TotalDeposited).Name("TOTAL_DEPOSITED")
                .Member(m => m.TotalPromotions).Name("TOTAL_PROMOTIONS")
                .Member(m => m.TotalVat).Name("TOTAL_VAT")
                .Member(m => m.TotalGross).Name("TOTAL_GROSS")
                .Member(m => m.TotalNet).Name("TOTAL_NET")
                .Member(m => m.Einvoice).Name("EINVOICE")
                .Member(m => m.EinvoiceType).Name("EINVOICE_TYPE")
                .Member(m => m.EinvoiceDriverName1).Name("EINVOICE_DRIVERNAME1")
                .Member(m => m.EinvoiceDriverSurname1).Name("EINVOICE_DRIVERSURNAME1")
                .Member(m => m.EinvoiceDriverTckno1).Name("EINVOICE_DRIVERTCKNO1")
                .Member(m => m.EinvoicePlateNum1).Name("EINVOICE_PLATENUM1")
                .Member(m => m.EinvoiceChassisNum1).Name("EINVOICE_CHASSISNUM1")
                .Member(m => m.EarchivedetrSendmod).Name("EARCHIVEDETR_SENDMOD")
                .Member(m => m.EarchivedetrIntpaymentType).Name("EARCHIVEDETR_INTPAYMENTTYPE")
                .Member(m => m.EarchivedetrDriverName1).Name("EARCHIVEDETR_DRIVERNAME1")
                .Member(m => m.EarchivedetrDriverSurname1).Name("EARCHIVEDETR_DRIVERSURNAME1")
                .Member(m => m.EarchivedetrDriverTckno1).Name("EARCHIVEDETR_DRIVERTCKNO1")
                .Member(m => m.EarchivedetrPlateNum1).Name("EARCHIVEDETR_PLATENUM1")
                .Member(m => m.EarchivedetrChassisNum1).Name("EARCHIVEDETR_CHASSISNUM1")
                .Member(m => m.VatExceptReason).Name("VATEXCEPT_REASON")
                .Member(m => m.VatExceptCode).Name("VATEXCEPT_CODE")
                .Member(m => m.RcRate).Name("RC_RATE")
                .Member(m => m.RcNet).Name("RC_NET")
                .Member(m => m.PrintCounter).Name("PRINT_COUNTER")
                .Member(m => m.SalesmanCode).Name("SALESMANCODE")
                .Member(m => m.GlPostCancl).Name("GL_POST_CANCL")
                .Member(m => m.ShipmentType).Name("SHIPMENT_TYPE")
                .Member(m => m.ShippingAgent).Name("SHIPPING_AGENT")
                .Member(m => m.TrackNr).Name("TRACK_NR")
                .Member(m => m.CurrselTotals).Name("CURRSEL_TOTALS")
                .Member(m => m.CurrselDetails).Name("CURRSEL_DETAILS")
                .Member(m => m.TextInc).Name("TEXTINC")
                .Member(m => m.OrigNumber).Name("ORIG_NUMBER")
                .Member(m => m.DlvClient).Name("DLV_CLIENT")
                .Member(m => m.DocTrackingNr).Name("DOC_TRACKING_NR")
                .Member(m => m.UDocTrackingNr).Name("U_DOC_TRACKING_NR")
                .Member(m => m.AddTaxCalc).Name("ADD_TAX_CALC")
                .Member(m => m.TotalAddTax).Name("TOTAL_ADD_TAX")
                .Member(m => m.VaAccCode).Name("VA_ACCCODE")
                .Member(m => m.VaCenterCode).Name("VA_CENTERCODE")
                .Member(m => m.FromExim).Name("FROM_EXIM")
                .Member(m => m.FrgTypeCode).Name("FRG_TYP_CODE")
                .Member(m => m.EximWhFicheRef).Name("EXIM_WH_FICHEREF")
                .Member(m => m.EximWhFicheNo).Name("EXIM_WH_FICHENO")
                .Member(m => m.CurrTransaction).Name("CURR_TRANSACTION")
                .Member(m => m.TcRate).Name("TC_RATE")
                .Member(m => m.WfLowCrdref).Name("WFLOWCRDREF")
                .Member(m => m.UpdCurr).Name("UPDCURR")
                .Member(m => m.UpdTrCurr).Name("UPDTRCURR")
                .Member(m => m.TotalExAddTax).Name("TOTALEXADDTAX")
                .Member(m => m.AffectCollatrl).Name("AFFECT_COLLATRL")
                .Member(m => m.Status).Name("STATUS")
                .Member(m => m.GrpFirmTrans).Name("GRPFIRMTRANS")
                .Member(m => m.DeductionPart1).Name("DEDUCTIONPART1")
                .Member(m => m.DeductionPart2).Name("DEDUCTIONPART2")
                .Member(m => m.AffectRisk).Name("AFFECT_RISK")
                .Member(m => m.ExchinfoAddDiscounts).Name("EXCHINFO_ADD_DISCOUNTS")
                .Member(m => m.ExchinfoTotalDiscounts).Name("EXCHINFO_TOTAL_DISCOUNTS")
                .Member(m => m.ExchinfoTotalDiscounted).Name("EXCHINFO_TOTAL_DISCOUNTED")
                .Member(m => m.ExchinfoAddExpenses).Name("EXCHINFO_ADD_EXPENSES")
                .Member(m => m.ExchinfoTotalExpenses).Name("EXCHINFO_TOTAL_EXPENSES")
                .Member(m => m.ExchinfoDistExpenses).Name("EXCHINFO_DIST_EXPENSES")
                .Member(m => m.ExchinfoTotalDepozito).Name("EXCHINFO_TOTAL_DEPOZITO")
                .Member(m => m.ExchinfoTotalPromotions).Name("EXCHINFO_TOTAL_PROMOTIONS")
                .Member(m => m.ExchinfoVatIncGross).Name("EXCHINFO_VAT_INC_GROSS")
                .Member(m => m.ExchinfoTotalVat).Name("EXCHINFO_TOTAL_VAT")
                .Member(m => m.ExchinfoGrossTotal).Name("EXCHINFO_GROSS_TOTAL")
                .Member(m => m.ExchinfoTotalAddTax).Name("EXCHINFO_TOTAL_ADD_TAX")
                .Member(m => m.ExchinfoTotalExAddTax).Name("EXCHINFO_TOTAL_EX_ADD_TAX")
                .Member(m => m.ExchinfoBagkur).Name("EXCHINFO_BAGKUR")
                .Member(m => m.ExchinfoStopaj).Name("EXCHINFO_STOPAJ")
                .Member(m => m.ExchinfoSsdf).Name("EXCHINFO_SSDF")
                .Member(m => m.ExchinfoBorsa).Name("EXCHINFO_BORSA")
                .Member(m => m.ExchinfoKomisyon).Name("EXCHINFO_KOMISYON")
                .Member(m => m.ExchinfoKomKdv).Name("EXCHINFO_KOM_KDV")
                .Member(m => m.ExchinfoEk1).Name("EXCHINFO_EK1")
                .Member(m => m.ExchinfoEk2).Name("EXCHINFO_EK2")
                .Member(m => m.ExchinfoEk3).Name("EXCHINFO_EK3")
                .Member(m => m.ExchinfoEk4).Name("EXCHINFO_EK4")
                .Member(m => m.ExchinfoEk5).Name("EXCHINFO_EK5")
                .Member(m => m.DispStatus).Name("DISP_STATUS")
                .Member(m => m.ShipDate).Name("SHIP_DATE")
                .Member(m => m.ShipTime).Name("SHIP_TIME")
                .Member(m => m.DocTime).Name("DOC_TIME")
                .Member(m => m.Edespatch).Name("EDESPATCH")
                .Member(m => m.EdespatchStatus).Name("EDESPATCH_STATUS")
                .Member(m => m.AutofillSlDetails).Name("AUTOFILL_SLDETAILS")
                .Member(m => m.MainMfReference).Name("MAIN_MF_REFERENCE")
                .Member(m => m.MainMfSiteId).Name("MAIN_MF_SITEID")
                .Member(m => m.LockControlDef).Name("LOC_CONTROL_OFF")
                .Member(m => m.CampaingCode).Name("CAMPAIGN_CODE")
                ;
        }
    }
}
