using ExtendedXmlSerializer;
using ExtendedXmlSerializer.Configuration;
using Ies.Logo.DataType.Xml;

namespace Ies.Logo.DataType.Details
{
    public class DetailProfile : IConfigurationProfile
    {
        public static DetailProfile Default { get; } = new DetailProfile();

        private DetailProfile() { }

        public IConfigurationContainer Get(IConfigurationContainer parameter)
        {
            var configuration = parameter.Type<Detail>();

            Configure(configuration);

            return configuration;
        }

        public static void Configure<T>(ITypeConfiguration<T> typeConfigurations) where T : Detail
        {
            typeConfigurations.Configure();
            typeConfigurations.Name<T>("DETAIL");

            typeConfigurations
                .Member(m => m.SlDetails).Name("SL_DETAILS")
                .Member(m => m.ItemCode).Name("ITEM_CODE")
                .Member(m => m.LineType).Name("LINE_TYPE")
                .Member(m => m.Detline).Name("DETLINE")
                .Member(m => m.DetailLevel).Name("DETAIL_LEVEL")
                .Member(m => m.DiscexpCalc).Name("DISCEXP_CALC")
                .Member(m => m.LineNumber).Name("LINE_NUMBER")
                .Member(m => m.OrderReference).Name("ORDER_REFERENCE")
                .Member(m => m.OrderSite).Name("ORDER_SITE")
                .Member(m => m.DelvryCode).Name("DELVRY_CODE")
                .Member(m => m.Quantity).Name("QUANTITY")
                .Member(m => m.Price).Name("PRICE")
                .Member(m => m.Total).Name("TOTAL")
                .Member(m => m.NetTotal).Name("NET_TOTAL")
                .Member(m => m.CurrPrice).Name("CURR_PRICE")
                .Member(m => m.PcPrice).Name("PC_PRICE")
                .Member(m => m.CurrTrans).Name("CURR_TRANS")
                .Member(m => m.TcXrate).Name("TC_XRATE")
                .Member(m => m.RcXrate).Name("RC_XRATE")
                .Member(m => m.TcostDistr).Name("TCOST_DISTR")
                .Member(m => m.DiscountDistr).Name("DISCOUNT_DISTR")
                .Member(m => m.ExpenseDistr).Name("EXPENSE_DISTR")
                .Member(m => m.PromotionDistr).Name("PROMOTION_DISTR")
                .Member(m => m.DiscountPerc).Name("DISCOUNT_PERC")
                .Member(m => m.Description).Name("DESCRIPTION")
                .Member(m => m.VatIncluded).Name("VAT_INCLUDED")
                .Member(m => m.VatPerc).Name("VAT_PERC")
                .Member(m => m.VatAmnt).Name("VAT_AMNT")
                .Member(m => m.VatBase).Name("VAT_BASE")
                .Member(m => m.Composite).Name("COMPOSITE")
                .Member(m => m.RetCostType).Name("RET_COST_TYPE")
                .Member(m => m.SourceReference).Name("SOURCE_REFERENCE")
                .Member(m => m.RetCost).Name("RET_COST")
                .Member(m => m.CurrRetCost).Name("CURR_RET_COST")
                .Member(m => m.OutCost).Name("OUT_COST")
                .Member(m => m.CurrOutCost).Name("CURR_OUT_COST")
                .Member(m => m.FaregCode).Name("FAREG_CODE")
                .Member(m => m.FaStatus).Name("FA_STATUS")
                .Member(m => m.PriceAdjustment).Name("PRICE_ADJUSTMENT")
                .Member(m => m.CostAdjustmentPr).Name("COST_ADJUSTMENT_PR")
                .Member(m => m.NegprcAdjustment).Name("NEGPRC_ADJUSTMENT")
                .Member(m => m.RcPrjadjust).Name("RC_PRJADJUST")
                .Member(m => m.RcCostadjust).Name("RC_COSTADJUST")
                .Member(m => m.OutputIdcode).Name("OUTPUT_IDCODE")
                .Member(m => m.CostRate).Name("COST_RATE")
                .Member(m => m.QcStatus).Name("QC_STATUS")
                .Member(m => m.VendComm).Name("VEND_COMM")
                .Member(m => m.PrevOutCost).Name("PREV_OUT_COST")
                .Member(m => m.CostOfSaleGlCode).Name("COST_OF_SALE_GL_CODE")
                .Member(m => m.PurchGlCode).Name("PURCH_GL_CODE")
                .Member(m => m.CostOfSaleOhpCode).Name("COST_OF_SALE_OHP_CODE")
                .Member(m => m.PurchOhpCode).Name("PURCH_OHP_CODE")
                .Member(m => m.PrevOutCostCurr).Name("PREV_OUT_COST_CURR")
                .Member(m => m.EuVatAmount).Name("EU_VAT_AMOUNT")
                .Member(m => m.EuVatStatus).Name("EU_VAT_STATUS")
                .Member(m => m.PrRate).Name("PR_RATE")
                .Member(m => m.AddTaxRate).Name("ADD_TAX_RATE")
                .Member(m => m.AddTaxConvFact).Name("ADD_TAX_CONV_FACT")
                .Member(m => m.AddTaxAmount).Name("ADD_TAX_AMOUNT")
                .Member(m => m.AddTaxPrCost).Name("ADD_TAX_PRCOST")
                .Member(m => m.AddTaxRetCost).Name("ADD_TAX_RETCOST")
                .Member(m => m.AddTaxRetCostCurr).Name("ADD_TAX_RETCOSTCURR")
                .Member(m => m.GrossuInfo1).Name("GROSS_U_INFO1")
                .Member(m => m.GrossuInfo2).Name("GROSS_U_INFO2")
                .Member(m => m.AddTaxPrCostCurr).Name("ADD_TAX_PRCOSTCURR")
                .Member(m => m.AddTaxAccRef).Name("ADD_TAX_ACCREF")
                .Member(m => m.AddTaxCenterRef).Name("ADD_TAX_CENTERREF")
                .Member(m => m.AddTaxAmntIsUpd).Name("ADD_TAX_AMNT_IS_UPD")
                .Member(m => m.PlnSttransPerNr).Name("PLN_STTRANS_PER_NR")
                .Member(m => m.PordClsPlnAmnt).Name("PORD_CLS_PLN_AMNT")
                .Member(m => m.PlnSttransReference).Name("PLN_STTRANS_REFERENCE")
                .Member(m => m.PlnAmount).Name("PLN_AMOUNT")
                .Member(m => m.InflationIdx).Name("INFLATION_IDX")
                .Member(m => m.PrdordTotCoeff).Name("PRDORD_TOT_COEFF")
                .Member(m => m.DempeggedAmnt).Name("DEMPEGGED_AMNT")
                .Member(m => m.StdUnitCost).Name("STDUNIT_COST")
                .Member(m => m.StdrpUnitCost).Name("STDRPUNIT_COST")
                .Member(m => m.Infldx).Name("INFLDX")
                .Member(m => m.CostdiffAccCode).Name("COSTDIFF_ACCCODE")
                .Member(m => m.CostdiffCenCode).Name("COSTDIFF_CENCODE")
                .Member(m => m.AddtaxDiscAmnt).Name("ADDTAXDISC_AMNT")
                .Member(m => m.OrgLogoId).Name("ORGLOGOID")
                .Member(m => m.EximFicheNo).Name("EXIM_FICHENO")
                .Member(m => m.EximFileLineNr).Name("EXIM_FILELINENR")
                .Member(m => m.Month).Name("MONTH")
                .Member(m => m.Year).Name("YEAR")
                .Member(m => m.Pordsymountln).Name("PORDSYMOUTLN")
                .Member(m => m.Exaddtaxrate).Name("EXADDTAXRATE")
                .Member(m => m.Exaddtaxconvf).Name("EXADDTAXCONVF")
                .Member(m => m.ExAddTaxaCode).Name("EXADDTAXACODE")
                .Member(m => m.ExAddTaxCcode).Name("EXADDTAXCCODE")
                .Member(m => m.OthrAddTaxaCode).Name("OTHRADDTAXACODE")
                .Member(m => m.OthrAddTaxCcode).Name("OTHRADDTAXCCODE")
                .Member(m => m.ExAddTaxAmnt).Name("EXADDTAXAMNT")
                .Member(m => m.AffectCollatrl).Name("AFFECT_COLLATRL")
                .Member(m => m.EdtPrice).Name("EDT_PRICE")
                .Member(m => m.EdtCurr).Name("EDT_CURR")
                .Member(m => m.AddTaxEffectKdv).Name("ADD_TAX_EFFECT_KDV")
                .Member(m => m.AffectRisk).Name("AFFECT_RISK")
                .Member(m => m.ExclinePrice).Name("EXCLINE_PRICE")
                .Member(m => m.ExclineTotal).Name("EXCLINE_TOTAL")
                .Member(m => m.ExclineDistCost).Name("EXCLINE_DIST_COST")
                .Member(m => m.ExclineDistDisc).Name("EXCLINE_DIST_DISC")
                .Member(m => m.ExclineDistExp).Name("EXCLINE_DIST_EXP")
                .Member(m => m.ExclineDistProm).Name("EXCLINE_DIST_PROM")
                .Member(m => m.ExclineVatAmount).Name("EXCLINE_VAT_AMOUNT")
                .Member(m => m.ExclineVatMatrah).Name("EXCLINE_VAT_MATRAH")
                .Member(m => m.ExclineLineNet).Name("EXCLINE_LINE_NET")
                .Member(m => m.ExclineDistAddExp).Name("EXCLINE_DIST_ADD_EXP")
                .Member(m => m.ExclineNetDiscAmount).Name("EXCLINE_NET_DISC_AMOUNT")
                .Member(m => m.ExclineVatCalcDiff).Name("EXCLINE_VAT_CALC_DIFF")
                .Member(m => m.ExclineEuVatAmount).Name("EXCLINE_EU_VAT_AMOUNT")
                .Member(m => m.ExclineAddTaxAmount).Name("EXCLINE_ADD_TAX_AMOUNT")
                .Member(m => m.ExclineAddTaxConvFact).Name("EXCLINE_ADD_TAX_CONV_FACT")
                .Member(m => m.ExclineAddTaxDiscAmount).Name("EXCLINE_ADD_TAX_DISC_AMOUNT")
                .Member(m => m.ExclineExAddTaxAmount).Name("EXCLINE_EX_ADD_TAX_AMOUNT")
                .Member(m => m.ExclineExAddTaxConvf).Name("EXCLINE_EX_ADD_TAX_CONVF")
                .Member(m => m.AddTaxVatMatrah).Name("ADD_TAX_VAT_MATRAH")
                .Member(m => m.ExclineAddTaxVatMatrah).Name("EXCLINE_ADD_TAX_VAT_MATRAH")
                .Member(m => m.AddTaxGlobalCode).Name("ADDTAX_GLOBAL_CODE")
                .Member(m => m.UnitGlobalCode).Name("UNIT_GLOBAL_CODE")
                .Member(m => m.PayplGlobalCode).Name("PAYPL_GLOBAL_CODE")
                .Member(m => m.PrcurrGlobalCode).Name("PRCURR_GLOBAL_CODE")
                .Member(m => m.TrcurrGlobalCode).Name("TRCURR_GLOBAL_CODE")
                .Member(m => m.EdtcurrGlobalCode).Name("EDTCURR_GLOBAL_CODE")
                .Member(m => m.Prclistcode).Name("PRCLISTCODE")
                .Member(m => m.Prclisttype).Name("PRCLISTTYPE")
                .Member(m => m.AddTaxExceptReason).Name("ADDTAXEXCEPT_REASON")
                .Member(m => m.AddTaxExceptCode).Name("ADDTAXEXCEPT_CODE")
                .Member(m => m.DeducationPart1).Name("DEDUCTION_PART1")
                .Member(m => m.DeducationPart2).Name("DEDUCTION_PART2")
                .Member(m => m.Guid).Name("GUID")
                ;
        }
    }
}
