//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogoObjectService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogoObjectService.ISvc")]
    public interface ISvc
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/AppendDataObject", ReplyAction="http://tempuri.org/ISvc/AppendDataObjectResponse")]
        System.Threading.Tasks.Task<LogoObjectService.AppendDataObjectResponse> AppendDataObjectAsync(LogoObjectService.AppendDataObjectRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ReadDataObject", ReplyAction="http://tempuri.org/ISvc/ReadDataObjectResponse")]
        System.Threading.Tasks.Task<LogoObjectService.ReadDataObjectResponse> ReadDataObjectAsync(LogoObjectService.ReadDataObjectRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ReadDataObjectXML", ReplyAction="http://tempuri.org/ISvc/ReadDataObjectXMLResponse")]
        System.Threading.Tasks.Task<LogoObjectService.ReadDataObjectXMLResponse> ReadDataObjectXMLAsync(LogoObjectService.ReadDataObjectXMLRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/DeleteDataObject", ReplyAction="http://tempuri.org/ISvc/DeleteDataObjectResponse")]
        System.Threading.Tasks.Task<LogoObjectService.DeleteDataObjectResponse> DeleteDataObjectAsync(LogoObjectService.DeleteDataObjectRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/CalculateDataObject", ReplyAction="http://tempuri.org/ISvc/CalculateDataObjectResponse")]
        System.Threading.Tasks.Task<LogoObjectService.CalculateDataObjectResponse> CalculateDataObjectAsync(LogoObjectService.CalculateDataObjectRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/ExecQuery", ReplyAction="http://tempuri.org/ISvc/ExecQueryResponse")]
        System.Threading.Tasks.Task<LogoObjectService.ExecQueryResponse> ExecQueryAsync(LogoObjectService.ExecQueryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/DirectQuery", ReplyAction="http://tempuri.org/ISvc/DirectQueryResponse")]
        System.Threading.Tasks.Task<LogoObjectService.DirectQueryResponse> DirectQueryAsync(LogoObjectService.DirectQueryRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getValue", ReplyAction="http://tempuri.org/ISvc/getValueResponse")]
        System.Threading.Tasks.Task<LogoObjectService.getValueResponse> getValueAsync(LogoObjectService.getValueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getTableName", ReplyAction="http://tempuri.org/ISvc/getTableNameResponse")]
        System.Threading.Tasks.Task<string> getTableNameAsync(int TableNr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/printDoc", ReplyAction="http://tempuri.org/ISvc/printDocResponse")]
        System.Threading.Tasks.Task printDocAsync(short doctype, int docRef, string termCode, string designTitle, string printerCode, short printCnt, string securityCode, string LbsLoadPass);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getInfo", ReplyAction="http://tempuri.org/ISvc/getInfoResponse")]
        System.Threading.Tasks.Task<LogoObjectService.getInfoResponse> getInfoAsync(LogoObjectService.getInfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/getStockPriceList", ReplyAction="http://tempuri.org/ISvc/getStockPriceListResponse")]
        System.Threading.Tasks.Task<LogoObjectService.getStockPriceListResponse> getStockPriceListAsync(LogoObjectService.getStockPriceListRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISvc/UsableCampaignCards", ReplyAction="http://tempuri.org/ISvc/UsableCampaignCardsResponse")]
        System.Threading.Tasks.Task<LogoObjectService.UsableCampaignCardsResponse> UsableCampaignCardsAsync(LogoObjectService.UsableCampaignCardsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AppendDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AppendDataObjectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public AppendDataObjectRequest()
        {
        }
        
        public AppendDataObjectRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode)
        {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AppendDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AppendDataObjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public AppendDataObjectResponse()
        {
        }
        
        public AppendDataObjectResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status)
        {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public ReadDataObjectRequest()
        {
        }
        
        public ReadDataObjectRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode)
        {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public ReadDataObjectResponse()
        {
        }
        
        public ReadDataObjectResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status)
        {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObjectXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public ReadDataObjectXMLRequest()
        {
        }
        
        public ReadDataObjectXMLRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode)
        {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadDataObjectXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReadDataObjectXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public ReadDataObjectXMLResponse()
        {
        }
        
        public ReadDataObjectXMLResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status)
        {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDataObjectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string securityCode;
        
        public DeleteDataObjectRequest()
        {
        }
        
        public DeleteDataObjectRequest(int dataType, int dataReference, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode)
        {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDataObjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte status;
        
        public DeleteDataObjectResponse()
        {
        }
        
        public DeleteDataObjectResponse(string errorString, byte status)
        {
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculateDataObject", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalculateDataObjectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public CalculateDataObjectRequest()
        {
        }
        
        public CalculateDataObjectRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode)
        {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CalculateDataObjectResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CalculateDataObjectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public CalculateDataObjectResponse()
        {
        }
        
        public CalculateDataObjectResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status)
        {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecQuery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sqlText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string orderByText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public object resultXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        public ExecQueryRequest()
        {
        }
        
        public ExecQueryRequest(string sqlText, string orderByText, string securityCode, object resultXML, string errorString, byte status, string LbsLoadPass)
        {
            this.sqlText = sqlText;
            this.orderByText = orderByText;
            this.securityCode = securityCode;
            this.resultXML = resultXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExecQueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ExecQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object resultXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public byte status;
        
        public ExecQueryResponse()
        {
        }
        
        public ExecQueryResponse(object resultXML, string errorString, byte status)
        {
            this.resultXML = resultXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DirectQuery", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DirectQueryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string sqlText;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        public DirectQueryRequest()
        {
        }
        
        public DirectQueryRequest(string sqlText, string securityCode, string errorString, byte status, string LbsLoadPass)
        {
            this.sqlText = sqlText;
            this.securityCode = securityCode;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DirectQueryResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DirectQueryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public byte status;
        
        public DirectQueryResponse()
        {
        }
        
        public DirectQueryResponse(string errorString, byte status)
        {
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getValueRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public short Flag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int Value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool isFlag;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string securityCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string LbsLoadPass;
        
        public getValueRequest()
        {
        }
        
        public getValueRequest(short Flag, int Value, bool isFlag, string securityCode, string LbsLoadPass)
        {
            this.Flag = Flag;
            this.Value = Value;
            this.isFlag = isFlag;
            this.securityCode = securityCode;
            this.LbsLoadPass = LbsLoadPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getValueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getValueResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int Value;
        
        public getValueResponse()
        {
        }
        
        public getValueResponse(int Value)
        {
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object resultXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string securityCode;
        
        public getInfoRequest()
        {
        }
        
        public getInfoRequest(object resultXML, string securityCode)
        {
            this.resultXML = resultXML;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public object resultXML;
        
        public getInfoResponse()
        {
        }
        
        public getInfoResponse(object resultXML)
        {
            this.resultXML = resultXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStockPriceList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getStockPriceListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string priceParamJson;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string priceListJson;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string securityCode;
        
        public getStockPriceListRequest()
        {
        }
        
        public getStockPriceListRequest(string priceParamJson, string priceListJson, string securityCode)
        {
            this.priceParamJson = priceParamJson;
            this.priceListJson = priceListJson;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStockPriceListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getStockPriceListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string priceListJson;
        
        public getStockPriceListResponse()
        {
        }
        
        public getStockPriceListResponse(string priceListJson)
        {
            this.priceListJson = priceListJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsableCampaignCards", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsableCampaignCardsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string LbsLoadPass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int FirmNr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string securityCode;
        
        public UsableCampaignCardsRequest()
        {
        }
        
        public UsableCampaignCardsRequest(int dataType, int dataReference, string dataXML, string paramXML, string errorString, byte status, string LbsLoadPass, int FirmNr, string securityCode)
        {
            this.dataType = dataType;
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
            this.LbsLoadPass = LbsLoadPass;
            this.FirmNr = FirmNr;
            this.securityCode = securityCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UsableCampaignCardsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UsableCampaignCardsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int dataReference;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string dataXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramXML;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string errorString;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public byte status;
        
        public UsableCampaignCardsResponse()
        {
        }
        
        public UsableCampaignCardsResponse(int dataReference, string dataXML, string paramXML, string errorString, byte status)
        {
            this.dataReference = dataReference;
            this.dataXML = dataXML;
            this.paramXML = paramXML;
            this.errorString = errorString;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISvcChannel : LogoObjectService.ISvc, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SvcClient : System.ServiceModel.ClientBase<LogoObjectService.ISvc>, LogoObjectService.ISvc
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SvcClient() : 
                base(SvcClient.GetDefaultBinding(), SvcClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISvc.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SvcClient(EndpointConfiguration endpointConfiguration) : 
                base(SvcClient.GetBindingForEndpoint(endpointConfiguration), SvcClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SvcClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SvcClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SvcClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SvcClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.AppendDataObjectResponse> AppendDataObjectAsync(LogoObjectService.AppendDataObjectRequest request)
        {
            return base.Channel.AppendDataObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.ReadDataObjectResponse> ReadDataObjectAsync(LogoObjectService.ReadDataObjectRequest request)
        {
            return base.Channel.ReadDataObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.ReadDataObjectXMLResponse> ReadDataObjectXMLAsync(LogoObjectService.ReadDataObjectXMLRequest request)
        {
            return base.Channel.ReadDataObjectXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.DeleteDataObjectResponse> DeleteDataObjectAsync(LogoObjectService.DeleteDataObjectRequest request)
        {
            return base.Channel.DeleteDataObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.CalculateDataObjectResponse> CalculateDataObjectAsync(LogoObjectService.CalculateDataObjectRequest request)
        {
            return base.Channel.CalculateDataObjectAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.ExecQueryResponse> ExecQueryAsync(LogoObjectService.ExecQueryRequest request)
        {
            return base.Channel.ExecQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.DirectQueryResponse> DirectQueryAsync(LogoObjectService.DirectQueryRequest request)
        {
            return base.Channel.DirectQueryAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.getValueResponse> getValueAsync(LogoObjectService.getValueRequest request)
        {
            return base.Channel.getValueAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> getTableNameAsync(int TableNr)
        {
            return base.Channel.getTableNameAsync(TableNr);
        }
        
        public System.Threading.Tasks.Task printDocAsync(short doctype, int docRef, string termCode, string designTitle, string printerCode, short printCnt, string securityCode, string LbsLoadPass)
        {
            return base.Channel.printDocAsync(doctype, docRef, termCode, designTitle, printerCode, printCnt, securityCode, LbsLoadPass);
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.getInfoResponse> getInfoAsync(LogoObjectService.getInfoRequest request)
        {
            return base.Channel.getInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.getStockPriceListResponse> getStockPriceListAsync(LogoObjectService.getStockPriceListRequest request)
        {
            return base.Channel.getStockPriceListAsync(request);
        }
        
        public System.Threading.Tasks.Task<LogoObjectService.UsableCampaignCardsResponse> UsableCampaignCardsAsync(LogoObjectService.UsableCampaignCardsRequest request)
        {
            return base.Channel.UsableCampaignCardsAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISvc))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISvc))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.20/LogoObjectService/Service");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SvcClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISvc);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SvcClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISvc);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISvc,
        }
    }
}
