using ExtendedXmlSerializer;
using ExtendedXmlSerializer.Configuration;
using Ies.Logo.DataType.Xml;

namespace Ies.Logo.DataType.MaterialSlips
{
    public class TransactionProfile : IConfigurationProfile
    {
        public static TransactionProfile Default { get; } = new TransactionProfile();

        private TransactionProfile() { }

        public IConfigurationContainer Get(IConfigurationContainer parameter)
        {
            var configuration = parameter.Type<Transaction>();

            Configure(configuration);

            return configuration;
        }

        public static void Configure<T>(ITypeConfiguration<T> typeConfigurations) where T : Transaction
        {
            typeConfigurations.Configure();
            typeConfigurations.Name<T>("TRANSACTION");

            typeConfigurations
                .Member(m => m.ItemCode).Name("ITEM_CODE")
                .Member(m => m.LineType).Name("LINE_TYPE")
                .Member(m => m.DetailLevel).Name("DETAIL_LEVEL")
                .Member(m => m.DiscexpCalc).Name("DISCEXP_CALC")
                .Member(m => m.PrordSite).Name("PRORD_SITE")
                .Member(m => m.PrordReference).Name("PRORD_REFERENCE")
                .Member(m => m.Sourcecostgrp).Name("SOURCECOSTGRP")
                .Member(m => m.Destindex).Name("DESTINDEX")
                .Member(m => m.Destcostgrp).Name("DESTCOSTGRP")
                .Member(m => m.Factorynr).Name("FACTORYNR")
                .Member(m => m.LineNumber).Name("LINE_NUMBER")
                .Member(m => m.DelvryCode).Name("DELVRY_CODE")
                .Member(m => m.Quantity).Name("QUANTITY")
                .Member(m => m.Price).Name("PRICE")
                .Member(m => m.Total).Name("TOTAL")
                .Member(m => m.NetTotal).Name("NET_TOTAL")
                .Member(m => m.CurrPrice).Name("CURR_PRICE")
                .Member(m => m.PcPrice).Name("PC_PRICE")
                .Member(m => m.CurrTrans).Name("CURR_TRANS")
                .Member(m => m.TcXrate).Name("TC_XRATE")
                .Member(m => m.RcXrate).Name("RC_XRATE")
                .Member(m => m.TcostDistr).Name("TCOST_DISTR")
                .Member(m => m.DiscountDistr).Name("DISCOUNT_DISTR")
                .Member(m => m.ExpenseDistr).Name("EXPENSE_DISTR")
                .Member(m => m.PromotionDistr).Name("PROMOTION_DISTR")
                .Member(m => m.DiscountPerc).Name("DISCOUNT_PERC")
                .Member(m => m.Description).Name("DESCRIPTION")
                .Member(m => m.UnitCode).Name("UNIT_CODE")
                .Member(m => m.UnitConv1).Name("UNIT_CONV1")
                .Member(m => m.UnitConv2).Name("UNIT_CONV2")
                .Member(m => m.UnitConv3).Name("UNIT_CONV3")
                .Member(m => m.UnitConv4).Name("UNIT_CONV4")
                .Member(m => m.UnitConv5).Name("UNIT_CONV5")
                .Member(m => m.UnitConv6).Name("UNIT_CONV6")
                .Member(m => m.UnitConv7).Name("UNIT_CONV7")
                .Member(m => m.UnitConv8).Name("UNIT_CONV8")
                .Member(m => m.VatIncluded).Name("VAT_INCLUDED")
                .Member(m => m.VatPerc).Name("VAT_PERC")
                .Member(m => m.VatAmnt).Name("VAT_AMNT")
                .Member(m => m.VatBase).Name("VAT_BASE")
                .Member(m => m.Composit).Name("COMPOSITE")
                .Member(m => m.RetCostType).Name("RET_COST_TYPE")
                .Member(m => m.RetCost).Name("RET_COST")
                .Member(m => m.CurrRetCost).Name("CURR_RET_COST")
                .Member(m => m.OutCost).Name("OUT_COST")
                .Member(m => m.CurrOutCost).Name("CURR_OUT_COST")
                .Member(m => m.RetQuantity).Name("RET_QUANTITY")
                .Member(m => m.FaregCode).Name("FAREG_CODE")
                .Member(m => m.FaStatus).Name("FA_STATUS")
                .Member(m => m.CostAdjustmentPr).Name("COST_ADJUSTMENT_PR")
                .Member(m => m.NegprcAdjustment).Name("NEGPRC_ADJUSTMENT")
                .Member(m => m.RcPrjadjust).Name("RC_PRJADJUST")
                .Member(m => m.RcCostadjust).Name("RC_COSTADJUST")
                .Member(m => m.OutputIdcode).Name("OUTPUT_IDCODE")
                .Member(m => m.CostRate).Name("COST_RATE")
                .Member(m => m.QcStatus).Name("QC_STATUS")
                .Member(m => m.VendComm).Name("VEND_COMM")
                .Member(m => m.PrevOutCost).Name("PREV_OUT_COST")
                .Member(m => m.CostOfSaleGlCode).Name("COST_OF_SALE_GL_CODE")
                .Member(m => m.PurchGlCode).Name("PURCH_GL_CODE")
                .Member(m => m.CostOfSaleOhpCode).Name("COST_OF_SALE_OHP_CODE")
                .Member(m => m.PurchOhpCode).Name("PURCH_OHP_CODE")
                .Member(m => m.PrevOutCostCurr).Name("PREV_OUT_COST_CURR")
                .Member(m => m.EuVatAmount).Name("EU_VAT_AMOUNT")
                .Member(m => m.EuVatStatus).Name("EU_VAT_STATUS")
                .Member(m => m.PrRate).Name("PR_RATE")
                .Member(m => m.AddTaxRate).Name("ADD_TAX_RATE")
                .Member(m => m.AddTaxConvFact).Name("ADD_TAX_CONV_FACT")
                .Member(m => m.AddTaxAmount).Name("ADD_TAX_AMOUNT")
                .Member(m => m.AddTaxPrcost).Name("ADD_TAX_PRCOST")
                .Member(m => m.AddTaxRetcost).Name("ADD_TAX_RETCOST")
                .Member(m => m.AddTaxRetcostcurr).Name("ADD_TAX_RETCOSTCURR")
                .Member(m => m.GrossUInfo1).Name("GROSS_U_INFO1")
                .Member(m => m.GrossUInfo2).Name("GROSS_U_INFO2")
                .Member(m => m.AddTaxPrCostCurr).Name("ADD_TAX_PRCOSTCURR")
                .Member(m => m.AddTaxAmntIsUpd).Name("ADD_TAX_AMNT_IS_UPD")
                .Member(m => m.PlnSttransPerNr).Name("PLN_STTRANS_PER_NR")
                .Member(m => m.PordClsPlnAmnt).Name("PORD_CLS_PLN_AMNT")
                .Member(m => m.PlnSttransReference).Name("PLN_STTRANS_REFERENCE")
                .Member(m => m.PlnAmount).Name("PLN_AMOUNT")
                .Member(m => m.InflationIdx).Name("INFLATION_IDX")
                .Member(m => m.PrdordTotCoef).Name("PRDORD_TOT_COEF")
                .Member(m => m.DempeggedAmnt).Name("DEMPEGGED_AMNT")
                .Member(m => m.StdunitCost).Name("STDUNIT_COST")
                .Member(m => m.StdrpunitCost).Name("STDRPUNIT_COST")
                .Member(m => m.Infldx).Name("INFLDX")
                .Member(m => m.CostdiffAcccode).Name("COSTDIFF_ACCCODE")
                .Member(m => m.CostdiffCencode).Name("COSTDIFF_CENCODE")
                .Member(m => m.AddtaxdiscAmnt).Name("ADDTAXDISC_AMNT")
                .Member(m => m.OrgLogoId).Name("ORGLOGOID")
                .Member(m => m.EximFicheno).Name("EXIM_FICHENO")
                .Member(m => m.EximFilelinenr).Name("EXIM_FILELINENR")
                .Member(m => m.Orglinkref).Name("ORGLINKREF")
                .Member(m => m.Pordsymoutln).Name("PORDSYMOUTLN")
                .Member(m => m.Exaddtaxrate).Name("EXADDTAXRATE")
                .Member(m => m.Exaddtaxconvf).Name("EXADDTAXCONVF")
                .Member(m => m.Exaddtaxacode).Name("EXADDTAXACODE")
                .Member(m => m.Exaddtaxccode).Name("EXADDTAXCCODE")
                .Member(m => m.Othraddtaxacode).Name("OTHRADDTAXACODE")
                .Member(m => m.Othraddtaxccode).Name("OTHRADDTAXCCODE")
                .Member(m => m.Exaddtaxamnt).Name("EXADDTAXAMNT")
                .Member(m => m.AffectCollatrl).Name("AFFECT_COLLATRL")
                .Member(m => m.Variantcode).Name("VARIANTCODE")
                .Member(m => m.Variantname).Name("VARIANTNAME")
                .Member(m => m.Canconfig).Name("CANCONFIG")
                .Member(m => m.EdtPrice).Name("EDT_PRICE")
                .Member(m => m.EdtCurr).Name("EDT_CURR")
                .Member(m => m.ExclinePrice).Name("EXCLINE_PRICE")
                .Member(m => m.ExclineTotal).Name("EXCLINE_TOTAL")
                .Member(m => m.ExclineDistCost).Name("EXCLINE_DIST_COST")
                .Member(m => m.ExclineDistDisc).Name("EXCLINE_DIST_DISC")
                .Member(m => m.ExclineDistExp).Name("EXCLINE_DIST_EXP")
                .Member(m => m.ExclineDistProm).Name("EXCLINE_DIST_PROM")
                .Member(m => m.ExclineVatAmount).Name("EXCLINE_VAT_AMOUNT")
                .Member(m => m.ExclineVatMatrah).Name("EXCLINE_VAT_MATRAH")
                .Member(m => m.ExclineLineNet).Name("EXCLINE_LINE_NET")
                .Member(m => m.ExclineDistAddExp).Name("EXCLINE_DIST_ADD_EXP")
                .Member(m => m.ExclineNetDiscAmount).Name("EXCLINE_NET_DISC_AMOUNT")
                .Member(m => m.ExclineVatCalcDiff).Name("EXCLINE_VAT_CALC_DIFF")
                .Member(m => m.ExclineEuVatAmount).Name("EXCLINE_EU_VAT_AMOUNT")
                .Member(m => m.ExclineAddTaxAmount).Name("EXCLINE_ADD_TAX_AMOUNT")
                .Member(m => m.ExclineAddTaxConvFact).Name("EXCLINE_ADD_TAX_CONV_FACT")
                .Member(m => m.ExclineAddTaxDiscAmount).Name("EXCLINE_ADD_TAX_DISC_AMOUNT")
                .Member(m => m.ExclineExAddTaxAmount).Name("EXCLINE_EX_ADD_TAX_AMOUNT")
                .Member(m => m.ExclineExAddTaxConvf).Name("EXCLINE_EX_ADD_TAX_CONVF")
                .Member(m => m.AddTaxVatMatrah).Name("ADD_TAX_VAT_MATRAH")
                .Member(m => m.ExclineAddTaxVatMatrah).Name("EXCLINE_ADD_TAX_VAT_MATRAH")
                .Member(m => m.Reltranslnref).Name("RELTRANSLNREF")
                .Member(m => m.Fromtransfer).Name("FROMTRANSFER")
                .Member(m => m.MainMtReference).Name("MAIN_MT_REFERENCE")
                .Member(m => m.MainMtSiteid).Name("MAIN_MT_SITEID")
                .Member(m => m.Prclistcode).Name("PRCLISTCODE")
                .Member(m => m.Prclisttype).Name("PRCLISTTYPE")
                .Member(m => m.FaplGlCode).Name("FAPL_GL_CODE")
                .Member(m => m.FaplOhpCode).Name("FAPL_OHP_CODE")
                .Member(m => m.AuxilCode2).Name("AUXIL_CODE2")
                .Member(m => m.SlDetails).Name("SL_DETAILS")
                .Member(m => m.Details).Name("DETAILS")
                .Member(m => m.DefnFldsList).Name("DEFNFLDSLIST")
                ;
        }
    }
}
