
name: "Build and test"

on:
  push:
    branches: [ dev ]
    paths:
      - 'framework/**'
      - 'modules/**'

  pull_request:
    branches: [ dev ]
    paths:
      - 'framework/**'
      - 'modules/**'
      
env:
    Configuration: 'Debug'
    
jobs:

  build-test:
    runs-on: windows-latest
  
    strategy:
      matrix:
        include:
          - SolutionPath: 'framework/Ies.Logo.sln'
          - SolutionPath: 'modules/logo-app/Ies.LogoApp.sln'

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Restore NuGet
        run: dotnet restore ${{ matrix.SolutionPath }}
        
      - name: Build Project
        run: dotnet build ${{ matrix.SolutionPath }} --no-restore --configuration=${{ env.Configuration }}
         
      - name: Test Project
        run: dotnet test  ${{ matrix.SolutionPath }} --no-restore --no-build --configuration=${{ env.Configuration }} --verbosity normal
