
name: "Build and test"

on:
  push:
    branches: [ dev ]
    paths:
      - 'framework/**'

  pull_request:
    branches: [ dev ]
    paths:
      - 'framework/**'
      
env:
    SolutionPath: 'framework/Ies.Logo.sln'
    Configuration: 'Debug'
    
jobs:
  build-test:
    
    runs-on: ${{ matrix.os }}
  
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          
      - name: Restore NuGet
        run: dotnet restore ${{ env.SolutionPath }}
        
      - name: Build Project
        run: dotnet build ${{ env.SolutionPath }} --no-restore --configuration=${{ env.Configuration }}
         
      - name: Test Project
        run: dotnet test  ${{ env.SolutionPath }} --no-restore --no-build --configuration=${{ env.Configuration }} --verbosity normal
