
name: "Framework NuGet publish"

on:
  push:
    branches: [ rel ]
    paths:
      - 'framework/**'
      - 'modules/**'

env:
    PackagePath: '${{ github.workspace }}\packages'
    BuildVersion: '1.0.${{ github.run_number }}'
    PackageVersion: '1.0.${{ github.run_number }}'
    NugetSourceUrl: 'https://api.nuget.org/v3/index.json'
    Configuration: 'Release'
    
jobs:
  rel-publish:
  
    runs-on: windows-latest
    
    steps:
      
      - uses: actions/checkout@v2
      
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Build
        run: .\build.ps1 ${{ env.Configuration }} ${{ env.BuildVersion }} ${{ env.PackageVersion }}
        working-directory: .\resources\commands
        shell: powershell
        
      - name: Test
        run: .\test.ps1 ${{ env.Configuration }}
        working-directory: .\resources\commands
        shell: powershell

      - name: Pack
        run: .\pack.ps1 ${{ env.Configuration }} ${{ env.PackageVersion }} ${{ env.PackagePath }}
        working-directory: .\resources\commands
        shell: powershell

      - name: Push package
        run: dotnet nuget push ${{ env.PackagePath }}\*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NugetSourceUrl }}
        
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          tag: ${{ env.PackageVersion }}
          commit: ${{ github.SHA }}
